package mods.usefulfood;

import mods.usefulfood.items.ItemBottle;
import mods.usefulfood.items.ItemBowl;
import mods.usefulfood.items.ItemCheese;
import mods.usefulfood.items.ItemFoodDebug;
import mods.usefulfood.items.ItemFoodStick;
import mods.usefulfood.items.ItemFoodUF;
import mods.usefulfood.items.ItemJuice;
import mods.usefulfood.items.ItemMagicAppleJuice;
import mods.usefulfood.items.ItemMagicCake;
import mods.usefulfood.items.ItemMagicFruitSalad;
import mods.usefulfood.items.ItemMagicIceCream;
import mods.usefulfood.items.ItemReedUF;
import mods.usefulfood.items.ItemSoupUF;
import mods.usefulfood.items.ItemTea;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.potion.Potion;

public class UFItems 
{
	public static Item AppleJamBiscuit;
	public static Item AppleCake;
	public static Item AppleIceCream;
	public static Item applejuice;
	public static Item biscuit;
	public static Item breadslice;
	public static Item CactusJuice;
	public static Item caramel;
	public static Item caramelapple;
	public static Item CaramelBiscuit;
	public static Item CaramelCake;
	public static Item CaramelIceCream;
	public static Item carrotjuice;
	public static Item carrotpie;
	public static Item carrotsoup;
	public static Item Cheese;
	public static Item CheeseSandwich;
	public static Item chickenwich;
	public static Item chocobiscuit;
	public static Item ChocolateApple;
	public static Item chocolatebottle;
	public static Item ChocolateCake;
	public static Item chocolatecandy;
	public static Item chocolateicecream;
	public static Item cmarshmallow;
	public static Item debugfood;
	public static Item eggwich;
	public static Item fishnchips;
	public static Item FishSoup;
	public static Item fishwich;
	public static Item friedegg;
	public static Item fruitsalad;
	public static Item hotchocolatebottle;
	public static Item HotMilkBottle;
	public static Item icecream;
	public static Item jelly;
	public static Item magicapplejuice;
	public static Item MagicCake;
	public static Item magicfruitsalad;
	public static Item MagicIceCream;
	public static Item marshmallow;
	public static Item MelonIceCream;
	public static Item melonjuice;
	public static Item milkbottle;
	public static Item MuttonCooked;
	public static Item MuttonRaw;
	public static Item MuttonSandwich;
	public static Item porkwich;
	public static Item pumpkinbread;
	public static Item pumpkinsoup;
	public static Item RoastedSeeds;
	public static Item salad;
	public static Item Oatmeal;
	public static Item Spaghetti;
	public static Item SquidSandwich;
	public static Item SquidSushi;
	public static Item SquidTentacleCooked;
	public static Item SquidTentacleRaw;
	public static Item steakwich;
	public static Item sugarbiscuit;
	public static Item sugarcube;
	public static Item sushi;
	public static Item Tea;
	public static Item trailmix;
	public static Item Cereal;
	public static Item ChocolateCereal;
	public static Item FrenchFries;
	public static Item AppleJelly;
	public static Item MelonJelly;
	public static Item Donut;
	public static Item Oreo;
	public static Item CaramelToast;
	public static Item ChocolateToast;
	public static Item SugarToast;
	public static Item SugarPancake;
	public static Item AppleJamPanCake;
	public static Item AppleJamToast;
	public static Item AppleJam;
	public static Item Waffle;
	public static Item CaramelPanCake;
	public static Item ChocolatePanCake;
	public static Item MelonJamPanCake;
	public static Item MelonJamToast;
	public static Item MelonJamBiscuit;
	public static Item MelonJam;
	public static Item PanCakeDough;
	public static Item PanCake;
	
	public UFItems() 
	{
		milkbottle = new ItemBottle("MilkBottle", 0, 0.0F, true).setContainerItem(Items.glass_bottle);
		chocolatebottle = new ItemBottle("ChocolateMilkBottle", 3, 0.8F, true);
		Cheese = new ItemCheese("Cheese", 2, 0.6F, true);
		chocolatecandy = new ItemFoodUF("ChocolateBar", 6, 1.0F, false);
		fruitsalad = new ItemBowl("FruitSalad", 7, 0.6F, false);
		magicfruitsalad = new ItemMagicFruitSalad("MagicFruitSalad", 6, 0.6F, false).setPotionEffect(Potion.regeneration.id, 5, 0, 1.0F).setPotionEffect(Potion.resistance.id, 10, 0, 1.0F);
		sugarcube = new ItemFoodUF("SugarCube", 4, 0.1F, false).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		caramel = new ItemFoodUF("Caramel", 5, 0.2F, false).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		caramelapple = new ItemFoodStick("CaramelApple", 10, 0.5F, false).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		RoastedSeeds = new ItemFoodUF("RoastedSeeds", 1, 0.5F, false);
		friedegg = new ItemFoodUF("FriedEgg", 3, 0.4F, true);
		pumpkinsoup = new ItemSoupUF("PumpkinSoup", 5, 0.8F);
		salad = new ItemBowl("Salad", 3, 0.6F, false);
		Oatmeal = new ItemBowl("Oatmeal", 4, 0.6F, false);
		jelly = new ItemBowl("Jelly", 5, 0.3F, false).setPotionEffect(Potion.jump.id, 30, 0, 1.0F);
		marshmallow = new ItemFoodStick("RawMarshmallow", 3, 0.3F, false);
		cmarshmallow = new ItemFoodStick("CookedMarshmallow", 4, 0.3F, false);
		icecream = new ItemBowl("VanillaIceCream", 2, 0.3F, true);
		breadslice = new ItemFoodUF("BreadSlice", 1, 0.3F, false);
		porkwich = new ItemFoodUF("PorkChopSandwich", 11, 1.0F, true);
		steakwich = new ItemFoodUF("SteakSandwich", 11, 1.0F, true);
		fishwich = new ItemFoodUF("FishSandwich", 8, 1.0F, true);
		chickenwich = new ItemFoodUF("ChickenSandwich", 9, 1.0F, true);
		eggwich = new ItemFoodUF("EggSandwich", 6, 1.0F, true);
		biscuit = new ItemFoodUF("Biscuit", 1, 0.3F, true);
		trailmix = new ItemBowl("Trailmix", 4, 0.5F, false);

		AppleCake = new ItemReedUF(UFBlocks.AppleCake, "AppleCake").setMaxStackSize(1);
		ChocolateCake = new ItemReedUF(UFBlocks.ChocolateCake, "ChocolateCake").setMaxStackSize(1);
		MagicCake = new ItemMagicCake(UFBlocks.MagicCake, "MagicCake").setMaxStackSize(1);

		// 1.0
		MuttonCooked = new ItemFoodUF("CookedMutton", 6, 0.8F, true);
		MuttonRaw = new ItemFoodUF("RawMutton", 3, 0.3F, true);
		MuttonSandwich = new ItemFoodUF("MuttonSandwich", 9, 1.0F, true);

		// 1.1
		debugfood = new ItemFoodDebug("Hungrz");
		
		// 1.2
		sushi = new ItemFoodUF("Sushi", 5, 0.3F, true);
		SquidTentacleRaw = new ItemFoodUF("SquidTentacle", 2, 0.3F, true);
		SquidTentacleCooked = new ItemFoodUF("CookedSquidTentacle", 5, 0.8F, true);
		SquidSandwich = new ItemFoodUF("SquidSandwich", 8, 0.8F, true);
		magicapplejuice = new ItemMagicAppleJuice("MagicAppleJuice", 13, 1.2F);
		melonjuice = new ItemJuice("MelonJuice", 6, 0.9F);
		applejuice = new ItemJuice("AppleJuice", 12, 0.9F);
		carrotjuice = new ItemJuice("CarrotJuice", 12, 0.9F);
		carrotsoup = new ItemSoupUF("CarrotSoup", 9, 0.8F);
		pumpkinbread = new ItemFoodUF("PumpkinBread", 10, 0.6F, true);
		fishnchips = new ItemFoodUF("FishnChips", 12, 1.2F, true);
		sugarbiscuit = new ItemFoodUF("SugarBiscuit", 3, 0.3F, false);
		AppleJamBiscuit = new ItemFoodUF("AppleJamBiscuit", 10, 0.3F, false);
		chocobiscuit = new ItemFoodUF("ChocolateBiscuit", 3, 1.0F, false);
		carrotpie = new ItemFoodUF("CarrotPie", 9, 0.8F, true);
		hotchocolatebottle = new ItemBottle("HotChocolateMilkBottle", 4, 1.0F, true).setContainerItem(Items.glass_bottle);
		chocolateicecream = new ItemBowl("ChocolateIceCream", 9, 0.8F, true);
		
		// 1.4
		MagicIceCream = new ItemMagicIceCream("MagicIceCream", 9, 0.6F, true).setPotionEffect(Potion.regeneration.id, 5, 0, 1.0F).setPotionEffect(Potion.resistance.id, 10, 0, 1.0F);
		SquidSushi = new ItemFoodUF("SquidSushi", 5, 0.3F, true);
		CactusJuice = new ItemJuice("CactusJuice", 5, 0.6F); 
		Spaghetti = new ItemBowl("Spaghetti", 5, 0.6F, false);
		AppleIceCream = new ItemBowl("AppleIceCream", 5, 0.6F, true);
		MelonIceCream = new ItemBowl("MelonIceCream", 7, 0.6F, true);
		ChocolateApple = new ItemFoodStick("ChocolateApple", 11, 0.6F, false);
		CaramelBiscuit = new ItemFoodUF("CaramelBiscuit", 7, 0.6F, false).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		FishSoup = new ItemSoupUF("FishSoup", 12, 0.6F);
		Tea = new ItemTea("Tea", 2);
		HotMilkBottle = new ItemBottle("HotMilkBottle", 1, 0.3F, true).setContainerItem(Items.glass_bottle);
		CaramelCake = new ItemReedUF(UFBlocks.CaramelCake, "CaramelCake").setMaxStackSize(1);
		CheeseSandwich = new ItemFoodUF("CheeseSandwich", 5, 1.0F, false);
		CaramelIceCream = new ItemBowl("CaramelIceCream", 8, 0.6F, true).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		Cereal = new ItemBowl("Cereal", 4, 0.5F, true);
		ChocolateCereal = new ItemBowl("ChocolateCereal", 6, 0.5F, true);
		FrenchFries = new ItemFoodUF("FrenchFries", 7, 0.6F, false); 
		AppleJelly = new ItemBowl("AppleJelly", 9, 0.4F, false).setPotionEffect(Potion.jump.id, 30, 0, 1.0F);
		MelonJelly = new ItemBowl("MelonJelly", 7, 0.4F, false).setPotionEffect(Potion.jump.id, 30, 0, 1.0F);
		Donut = new ItemFoodUF("Donut", 7, 0.6F, false);
		Oreo = new ItemFoodUF("Oreo", 9, 1.0F, false);
		CaramelToast = new ItemFoodUF("CaramelToast", 7, 0.6F, false).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		ChocolateToast = new ItemFoodUF("ChocolateToast", 8, 0.6F, false);
		SugarToast = new ItemFoodUF("SugarToast", 3, 0.2F, false).setPotionEffect(Potion.moveSpeed.id, 5, 0, 1.0F);
		SugarPancake = new ItemFoodUF("SugarPancake", 8, 0.6F, false).setPotionEffect(Potion.moveSpeed.id, 5, 0, 1.0F);
		AppleJamPanCake = new ItemFoodUF("AppleJamPancake", 15, 0.7F, false);
		AppleJamToast = new ItemFoodUF("AppleJamToast", 10, 0.7F, false);
		AppleJam = new ItemBowl("AppleJam", 8, 0.4F, false).setContainerItem(Items.bowl);
		CaramelPanCake = new ItemFoodUF("CaramelPancake", 12, 0.6F, false).setPotionEffect(Potion.moveSpeed.id, 10, 0, 1.0F);
		ChocolatePanCake = new ItemFoodUF("ChocolatePancake", 13, 0.6F, false);
		MelonJamPanCake = new ItemFoodUF("MelonJamPancake", 13, 0.4F, false);
		MelonJamToast = new ItemFoodUF("MelonJamToast", 8, 0.4F, false);
		MelonJamBiscuit = new ItemFoodUF("MelonJamBiscuit", 8, 0.4F, false);
		MelonJam = new ItemBowl("MelonJam", 6, 0.4F, false).setContainerItem(Items.bowl);
		PanCakeDough = new ItemFoodUF("PancakeDough", 5, 0.3F, false);
		PanCake = new ItemFoodUF("Pancake", 6, 0.6F, false);
	}
}
